// Mapping: FIFA 3-letter code → { name (Deutsch), flagcdn code }
export const COUNTRIES: Record<string, { name: string; flag: string }> = {
  // Gruppe A–F WM 2026 (48 Teams)
  USA: { name: 'USA', flag: 'us' },
  MEX: { name: 'Mexiko', flag: 'mx' },
  CAN: { name: 'Kanada', flag: 'ca' },
  BRA: { name: 'Brasilien', flag: 'br' },
  ARG: { name: 'Argentinien', flag: 'ar' },
  URU: { name: 'Uruguay', flag: 'uy' },
  COL: { name: 'Kolumbien', flag: 'co' },
  ECU: { name: 'Ecuador', flag: 'ec' },
  CHI: { name: 'Chile', flag: 'cl' },
  PAR: { name: 'Paraguay', flag: 'py' },
  PER: { name: 'Peru', flag: 'pe' },
  BOL: { name: 'Bolivien', flag: 'bo' },
  VEN: { name: 'Venezuela', flag: 've' },
  GER: { name: 'Deutschland', flag: 'de' },
  FRA: { name: 'Frankreich', flag: 'fr' },
  ESP: { name: 'Spanien', flag: 'es' },
  ENG: { name: 'England', flag: 'gb-eng' },
  POR: { name: 'Portugal', flag: 'pt' },
  NED: { name: 'Niederlande', flag: 'nl' },
  BEL: { name: 'Belgien', flag: 'be' },
  ITA: { name: 'Italien', flag: 'it' },
  SUI: { name: 'Schweiz', flag: 'ch' },
  AUT: { name: 'Österreich', flag: 'at' },
  CRO: { name: 'Kroatien', flag: 'hr' },
  DEN: { name: 'Dänemark', flag: 'dk' },
  SWE: { name: 'Schweden', flag: 'se' },
  NOR: { name: 'Norwegen', flag: 'no' },
  POL: { name: 'Polen', flag: 'pl' },
  UKR: { name: 'Ukraine', flag: 'ua' },
  SRB: { name: 'Serbien', flag: 'rs' },
  HUN: { name: 'Ungarn', flag: 'hu' },
  CZE: { name: 'Tschechien', flag: 'cz' },
  SVK: { name: 'Slowakei', flag: 'sk' },
  ROU: { name: 'Rumänien', flag: 'ro' },
  SCO: { name: 'Schottland', flag: 'gb-sct' },
  TUR: { name: 'Türkei', flag: 'tr' },
  GRE: { name: 'Griechenland', flag: 'gr' },
  ALB: { name: 'Albanien', flag: 'al' },
  WAL: { name: 'Wales', flag: 'gb-wls' },
  RSA: { name: 'Südafrika', flag: 'za' },
  MAR: { name: 'Marokko', flag: 'ma' },
  SEN: { name: 'Senegal', flag: 'sn' },
  NGA: { name: 'Nigeria', flag: 'ng' },
  GHA: { name: 'Ghana', flag: 'gh' },
  CIV: { name: 'Elfenbeinküste', flag: 'ci' },
  CMR: { name: 'Kamerun', flag: 'cm' },
  EGY: { name: 'Ägypten', flag: 'eg' },
  ALG: { name: 'Algerien', flag: 'dz' },
  TUN: { name: 'Tunesien', flag: 'tn' },
  MLI: { name: 'Mali', flag: 'ml' },
  JPN: { name: 'Japan', flag: 'jp' },
  KOR: { name: 'Südkorea', flag: 'kr' },
  AUS: { name: 'Australien', flag: 'au' },
  IRN: { name: 'Iran', flag: 'ir' },
  SAU: { name: 'Saudi-Arabien', flag: 'sa' },
  QAT: { name: 'Katar', flag: 'qa' },
  IRQ: { name: 'Irak', flag: 'iq' },
  ISR: { name: 'Israel', flag: 'il' },
  JOR: { name: 'Jordanien', flag: 'jo' },
  CHN: { name: 'China', flag: 'cn' },
  IND: { name: 'Indien', flag: 'in' },
  UZB: { name: 'Usbekistan', flag: 'uz' },
  NZL: { name: 'Neuseeland', flag: 'nz' },
  PAN: { name: 'Panama', flag: 'pa' },
  CRC: { name: 'Costa Rica', flag: 'cr' },
  HON: { name: 'Honduras', flag: 'hn' },
  JAM: { name: 'Jamaika', flag: 'jm' },
}

export function getCountryName(code: string): string {
  return COUNTRIES[code]?.name ?? code
}

export function getFlagUrl(code: string): string {
  const flag = COUNTRIES[code]?.flag ?? code.toLowerCase()
  return `https://flagcdn.com/24x18/${flag}.png`
}
